### PR TITLE
[WIP] Jspm 0.16 Compatibility

### PR DESCRIPTION
**Pull request by johnraz**
Hot reloading of regular es6 module seems ok, jsx is broken and I have so far no idea why ^^

### CODE REVIEW

**Comment by johnraz** [comment]
ok I just realized that #25 is solving about the same issue but I don't believe JSX is fixed there either.

@Globegitter did you test jsx hot reloading ?

**Comment by johnraz** [comment]
Further investigation regarding jsx showed that using it as regular javascript file, without any loader, actually made hot reloading work for react component.

I'm not sure if the state is persisted, didn't try yet, and my guess would be no, as no react hot api is used now...

I really need to dig this further at several level:
- I need to better understand how react-hot-api is and should be used.
- I need to better understand how systemjs uses plugins and loaders and how the actual jsx-loader is working.

If anybody has information about these topic, that would be nice :-)

**Comment by johnraz** [comment]
Ok as expected, the state is not persisted.

Gently pinging @geelen and @guybedford for ideas on keeping this working.

**Comment by guybedford** [comment]
@johnraz I haven't followed this work too closely, but if you have any specific questions I'm happy to answer them.

**Comment by johnraz** [comment]
ok back to business after a sweet trip, still have some days off at home \o/

@guybedford, I do have 1 specific request:

Could you give a look at https://github.com/johnraz/jspm-server/blob/jspm-0.16-compatibility/lib/change-handler.js and review the usage of systemJS there ? I want to make sure there is no better way to do that part with the latest systemJS api.

Thx !

**Pull request merged**
