### PR TITLE
replaced foxy proxy server with more robust solution

### PR DESCRIPTION
**Pull request by kevrom**
replaced the foxy proxy server, with a more robust proxy server solution to fix issue #10

### CODE REVIEW

**Comment by johnraz** [comment]
I gave it a go and while the JSPM watching issue seems to be gone, my main.js file is never executed with the new proxy module, any idea ? 

Side note, my browser seems to be loading something as I can see the loading icon spinning, but nothin in the network panel whatsoever ...

Edit: killing the jspm-server will let the page finish its loading and the javascript executes itself just fine but well, everything is then broken offcourse ;-)

Edit: Below is a screenshot of what the chrome network panel has to say about it
pie

Edit: After waiting a loooong time (2mn) it does actually work ... I have no clue how to analyze this. For the sake of clarity I don't have the 2mn latency issue when accessing the proxied server directly (which is django's dev server btw).
pie

**Comment by kevrom** [comment]
Interesting. Going to have to see if I can reproduce this somehow. I'm using a Koa server to test and I didn't have any problems. I'll spin up a Django server later today to test it. Thanks for the feedback!

**Comment by johnraz** [comment]
Ok further investigation today showed that it is related to the django dev server's way of handling static files. I have no idea about the specific issue yet on django's side (I'm on Django 1.6 for that project btw), but going through nginx to serve the static files solved the problem ... (off topic: I had to disable gzip compression in nginx to make it all work).

So I think we should :shipit:  @geelen

**Comment by kevrom** [comment]
Thanks for looking into it further, I didn't have time yesterday to play around with it.  I'll add a disable gzip header in another PR.  Thanks @johnraz

**Comment by kevrom** [comment]
Resolved merge conflicts
@johnraz I also added a request header that disables gzip compression.  If you don't mind testing it out, let me know if it plays well with Django.  It worked fine when I enabled gzip on my koa app.

**Comment by johnraz** [comment]
Just for the record, I will have some time to test this tomorrow ;-)

**Comment by johnraz** [comment]
@kevrom : tested the gzip header today, and it works perfectly fine ;-) Thanks !

**Comment by kevrom** [comment]
Thanks for looking into it.  Maybe we can get this thing merged?

**Comment by johnraz** [comment]
@geelen ? :-)

**Comment by geelen** [comment]
Sorry! Had head down on a consulting gig. Gonna test & merge this now

**Comment by geelen** [comment]
Looks good to me!

**Pull request merged**
