### PR TITLE
Inclusion filter

### PR DESCRIPTION
**Pull request by danieldunderfelt**
This is an inclusion filter feature for jspm-server:

Supply an `--only=""` argument when executing the command to trigger reloads only for the file extensions `only` contains. For example, a command like `jspm-server --only="js"` triggers reloads only for `.js` files. If you omit the `--only` option, or `--only=""` is empty, `jspm-server` will work just like before, triggering reloads for all files.

The list syntax for the `--only` option is pretty loose. It'll work as long as you delimit the extensions with a comma. You do not need the period in the extension either, but you're free to write it like that if you want. The following is thus valid: `--only=".js, jsx,html, .css"`.

### CODE REVIEW

**Comment by geelen** [comment]
This is great, but can I get you to add a couple of things? The first is some documentation about the argument to the Readme, the fact that it's a selector on _extensions_, not paths. If we later add an `--exclude` that will be path-based so I'd want to make the distinction clear.

The second is to run `browserify injected.src.js -t babelify --outfile injected.js` before each check-in. I ran it on your branch and got a diff, which is weird because your branch doesn't change any of the injections. I am 100% sure there is a better way to be devving on that than having to remember that each time, but I haven't figured it out yet. Sorry about that.

**Comment by danieldunderfelt** [comment]
Oh yes forgot about the readme. I'll fix it later today!

**Comment by danieldunderfelt** [comment]
Alright, readme file amended. I also snuck in an exclusion filter and changed the option syntax for the two filters slightly.

**Comment by geelen** [comment]
Looks great, README additions read well. Just gonna check this out and confirm it works as-described then merge & release. Thanks!

**Comment by geelen** [comment]
Weird, building it locally gave me a diff, but it all seems to work a-ok, so this is going in!

**Comment by danieldunderfelt** [comment]
Sweet! Not sure about the diff, maybe my editor did something to whitespace or something. If it works.... :D

**Pull request merged**
